name:                SPF
version:             0.1.0.0
github:              "Tinch334/SPF"
license:             GPL-3
author:              "Martín Goñi"
copyright:           "Martín Goñi"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Tinch334/SPF#readme>

dependencies:
- base >= 4.7 && < 5
- HPDF == 1.7
- text 
- random #Check necessity
- vector #Check necessity
- array #Check necessity
- network-uri #Check necessity
- filepath
- megaparsec >= 9.0
- optparse-applicative
- optparse-simple
- validation
- safe-coloured-text
- ghc-internal
- containers
- JuicyPixels
- bytestring
- async
- directory


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  SPF-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SPF

tests:
  SPF-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SPF
